"""Schemas (data contracts) for every dataset bundled with the project.

These are the single source of truth for ``docs/DATA_DICTIONARY.md``; regenerate it with
``pandasplayground docs data-dictionary``.
"""

from __future__ import annotations

import pandas as pd

from pandasplayground.validation import Check, Column, DataFrameSchema

REGIONS = ("East", "West", "Central", "South")
SEGMENTS = ("Consumer", "Corporate", "Home Office")
CATEGORIES = ("Furniture", "Office Supplies", "Technology")
SUB_CATEGORIES = (
    "Bookcases",
    "Chairs",
    "Tables",
    "Binders",
    "Pens",
    "Paper",
    "Labels",
    "Phones",
    "Accessories",
    "Copiers",
    "Machines",
)
DISCOUNTS = (0.0, 0.1, 0.2, 0.3, 0.5)
LOAN_PURPOSES = ("Car", "Home", "Education", "Business", "Medical", "Vacation")
LOAN_REGIONS = ("East", "West", "North", "South")
COUNTRIES = ("USA", "India", "Brazil", "Germany", "Canada")
VARIANTS = ("Alpha", "Delta", "Omicron", "BA.5", "XBB")
WEATHER_CONDITIONS = ("Sunny", "Rain", "Cloudy", "Storm", "Snow")


def _ship_not_before_order(df: pd.DataFrame) -> pd.Series:
    return pd.to_datetime(df["Ship Date"]) >= pd.to_datetime(df["Order Date"])


SUPERSTORE = DataFrameSchema(
    name="superstore_sales",
    description="Synthetic retail order lines (one row per order). File: `data/superstore_sales.csv`.",
    min_rows=1,
    columns=[
        Column("Order ID", "string", "Order identifier.", nullable=False, unique=True, pattern=r"ORD-\d{5,}"),
        Column(
            "Customer ID",
            "string",
            "Customer identifier (not unique: repeat customers).",
            nullable=False,
            pattern=r"CUST-\d{4}",
        ),
        Column("Customer Name", "string", "Synthetic full name generated by Faker.", nullable=False),
        Column("Segment", "string", "Customer segment.", nullable=False, allowed=SEGMENTS),
        Column("Region", "string", "US sales region.", nullable=False, allowed=REGIONS),
        Column(
            "Order Date",
            "string",
            "Order date (ISO-8601). Consecutive daily dates.",
            nullable=False,
            coerce_datetime=True,
        ),
        Column("Ship Date", "string", "Ship date (ISO-8601).", nullable=False, coerce_datetime=True),
        Column("Category", "string", "Product category.", nullable=False, allowed=CATEGORIES),
        Column("Sub-Category", "string", "Product sub-category.", nullable=False, allowed=SUB_CATEGORIES),
        Column("Product Name", "string", "Product label (`<Sub-Category> Model <n>`).", nullable=False),
        Column("Sales", "float", "Order revenue in USD.", nullable=False, min=0),
        Column("Quantity", "int", "Units ordered.", nullable=False, min=1),
        Column("Discount", "float", "Fractional discount applied.", nullable=False, allowed=DISCOUNTS),
        Column("Profit", "float", "Order profit in USD (may be negative).", nullable=False),
    ],
    checks=[
        Check("ship_date_on_or_after_order_date", _ship_not_before_order, "`Ship Date >= Order Date` for every row.")
    ],
)

BANK_LOANS = DataFrameSchema(
    name="bank_loans",
    description="Synthetic loan applications. File: `data/bank_loans.xlsx` (single sheet).",
    min_rows=1,
    columns=[
        Column("Customer_ID", "int", "Applicant identifier.", nullable=False, unique=True, min=1),
        Column("Customer_Name", "string", "Synthetic full name generated by Faker.", nullable=False),
        Column("Age", "int", "Applicant age in years.", nullable=False, min=18, max=100),
        Column("Income", "int", "Annual income in USD.", nullable=False, min=0),
        Column("Loan_Amount", "int", "Requested principal in USD.", nullable=False, min=0),
        Column("Loan_Purpose", "string", "Stated purpose of the loan.", nullable=False, allowed=LOAN_PURPOSES),
        Column("Approved", "string", "Approval decision.", nullable=False, allowed=("Yes", "No")),
    ],
)

BANK_LOANS_REGIONAL = DataFrameSchema(
    name="bank_loans_multisheet",
    description=(
        "One sheet per region in `data/bank_loans_multisheet.xlsx`. Each sheet is the full "
        "`bank_loans` table with a constant `Region` label, so customers repeat across sheets."
    ),
    min_rows=1,
    columns=[
        *BANK_LOANS.columns,
        Column("Region", "string", "Sheet/region label.", nullable=False, allowed=LOAN_REGIONS),
    ],
)

COVID = DataFrameSchema(
    name="covid_data",
    description="Synthetic daily epidemiological series. File: `data/covid_data.parquet`.",
    min_rows=1,
    columns=[
        Column("date", "datetime", "Observation date (one row per day).", nullable=False, unique=True),
        Column("country", "string", "Country label, randomly assigned per day.", nullable=False, allowed=COUNTRIES),
        Column(
            "variant", "string", "Dominant variant label, randomly assigned per day.", nullable=False, allowed=VARIANTS
        ),
        Column("new_cases", "int", "New cases, drawn from Poisson(500).", nullable=False, min=0),
        Column("new_deaths", "int", "New deaths, drawn from Poisson(10).", nullable=False, min=0),
        Column("hospitalized", "int", "Hospitalised count, Uniform{0..4999}.", nullable=False, min=0),
    ],
)

WEATHER = DataFrameSchema(
    name="weather_data",
    description="Synthetic daily weather observations. File: `data/weather_data.json` (records orient).",
    min_rows=1,
    columns=[
        Column(
            "date", "datetime", "Observation date (one row per day).", nullable=False, unique=True, coerce_datetime=True
        ),
        Column("temperature_c", "int", "Temperature in degrees Celsius.", nullable=False, min=-60, max=60),
        Column("humidity", "int", "Relative humidity (%).", nullable=False, min=0, max=100),
        Column("condition", "string", "Weather condition label.", nullable=False, allowed=WEATHER_CONDITIONS),
    ],
)

FINAL_MERGED = DataFrameSchema(
    name="final_merged_pipeline",
    description="Monthly sales joined to monthly COVID indicators. Output of `pandasplayground pipeline`.",
    min_rows=1,
    strict=True,
    columns=[
        Column(
            "month",
            "string",
            "Calendar month `YYYY-MM` (join key).",
            nullable=False,
            unique=True,
            pattern=r"\d{4}-\d{2}",
        ),
        Column("sales", "float", "Total monthly sales (USD).", nullable=False, min=0),
        Column("profit", "float", "Total monthly profit (USD).", nullable=False),
        Column("new_cases", "int", "Total monthly new cases.", nullable=False, min=0),
        Column("hospitalized", "float", "Mean daily hospitalised count in the month.", nullable=False, min=0),
        Column("rolling_profit", "float", "Trailing 3-month mean of `profit` (NaN for the first 2 months)."),
        Column("sales_pct_change", "float", "Month-over-month fractional change in `sales` (NaN for the first month)."),
    ],
    checks=[
        Check(
            "months_sorted_ascending",
            lambda df: bool(df["month"].is_monotonic_increasing),
            "Rows are ordered chronologically, which the rolling/percent-change features rely on.",
        )
    ],
)

RAW_SCHEMAS: dict[str, DataFrameSchema] = {
    "superstore_sales.csv": SUPERSTORE,
    "bank_loans.xlsx": BANK_LOANS,
    "covid_data.parquet": COVID,
    "weather_data.json": WEATHER,
}

ALL_SCHEMAS: tuple[DataFrameSchema, ...] = (SUPERSTORE, BANK_LOANS, BANK_LOANS_REGIONAL, COVID, WEATHER, FINAL_MERGED)
